name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Postavi Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instaliraj zavisnosti
        run: pip install -r requirements.txt

      - name: Pokreni testove
        run: pytest test_app.py -v

  lint:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        
        - name: Instaliraj flake8
          run: pip install flake8
        
        - name: Pokreni lint
          run: flake8 app.py --max-line-length=100

  docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
      - uses: actions/checkout@v4

      - name: Login na Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buildi i pushuj Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-learning:${{ github.sha }}